<?php

use DISMaja\Webtrees\Module\UnlinkedIndividual\Http\UnlinkedAction;
use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\GedcomTag;
use Fisharebest\Webtrees\Http\RequestHandlers\EditRawFactPage;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\SurnameTradition;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;
use Ramsey\Uuid\Uuid;

/**
 * @var Family|null     $family
 * @var string          $famtag
 * @var string          $gender
 * @var Individual|null $individual
 * @var Fact|null       $name_fact
 * @var string          $next_action
 * @var string          $title
 * @var Tree            $tree
 */

?>
<?php
#    $cancel_url = route(ManageTrees::class, ['tree' => $tree->name()]);
#    $cancel_url = str_replace(array('%2Fadmin','%2Fmanage'),'', $cancel_url);
#    $cancel_url = str_replace('%2Ftrees','%2Ftree', $cancel_url);
    $cancel_url = route(UnlinkedAction::class, ['tree' => $tree->name()]);
    $cancel_url = str_replace('%2Funlinked-individual','', $cancel_url);
    $xref       = 'new';

    // Creating a new name
    $name_fact_id = '';
    $namerec      = '';
    $name_fields  = [
#        'NAME' => '',
#        'TYPE' => '',
#        'NPFX' => '',
        'GIVN' => '',
#        'NICK' => '',
#        'SPFX' => '',
        'SURN' => '',
#        'NSFX' => '',
    ];

#    $father      = null;
#    $mother      = null;
#    $father_name = '';
#    $mother_name = '';

$bdm = ''; // used to copy '1 SOUR' to '2 SOUR' for BIRT DEAT MARR

?>
<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route($next_action, ['tree' => $tree->name(), 'xref' => $xref, 'fact_id' => $name_fact ? $name_fact->id() : null])) ?>" onsubmit="return checkform();">
    <input type="hidden" name="fact_id" value="<?= e($name_fact_id) ?>">
    <input type="hidden" name="famtag" value="<?= e($famtag) ?>">
    <input type="hidden" name="gender" value="<?= $gender ?>">
    <input type="hidden" name="NAME" value="">
    <input type="hidden" name="NPFX" value="">
    <input type="hidden" name="SPFX" value="">
    <input type="hidden" name="NSFX" value="">
    <input type="hidden" name="NICK" value="">
    <input type="hidden" name="_AKA" value="">
    <input type="hidden" name="_MARNM" value="">
    <?= csrf_field() ?>

    <?php
#    // If we are adding a new individual, choose the sex.
#    echo FunctionsEdit::addSimpleTag($tree, '0 SEX');
    ?>

    <?php
    $SEXid  = 'SEX'  . Uuid::uuid4()->toString();
    $GIVNid = 'GIVN' . Uuid::uuid4()->toString();
    $SURNid = 'SURN' . Uuid::uuid4()->toString();
    ?>
    
    <div class="form-group row">
	<label class="col-sm-3 col-form-label" for="<?= $SEXid ?>">
	    <?= I18N::translate('Gender') ?>
	</label>
	<div class="col-sm-9">
	    <div class="form-check form-check-inline">
	        <input type="radio" class="form-check-input" name ="SEX" id="SEX-M" value="M" required="required">
		<label class="form-check-label" for="SEX-M">
		    <?= I18N::translate('Male') ?>
		</label>
	    </div>
	    <div class="form-check form-check-inline">
	        <input type="radio" class="form-check-input" name ="SEX" id="SEX-F" value="F" required="required">
		<label class="form-check-label" for="SEX-F">
		    <?= I18N::translate('Female') ?>
		</label>
	    </div>
	    <div class="form-check form-check-inline">
	        <input type="radio" class="form-check-input"  name ="SEX" id="SEX-U" value="F" required="required">
		<label class="form-check-label" for="SEX-U">
		    <?= I18N::translate('Unknown') ?>
		</label>
	    </div>
	</div>
    </div>

    <div class="form-group row">
	<label class="col-sm-3 col-form-label" for="<?= $GIVNid ?>">
	    <?= I18N::translate('Given names') ?>
	</label>
	<div class="col-sm-9">
	    <div class="input-group">
		<input class="form-control" type="text" id="<?= $GIVNid ?>" name="GIVN" value="">
	    </div>
	</div>
    </div>

    <div class="form-group row">
	<label class="col-sm-3 col-form-label" for="<?= $SURNid ?>">
	    <?= I18N::translate('Surname') ?>
	</label>
	<div class="col-sm-9">
	    <div class="input-group">
		<input class="form-control" type="text" id="<?= $SURNid ?>" name="SURN" value="">
	    </div>
	</div>
    </div>

    <div class="row form-group">
        <div class="col-sm-9 offset-sm-3">
            <button class="btn btn-primary" type="submit">
                <?= view('icons/save') ?>
                <?= /* I18N: A button label. */
                I18N::translate('save') ?>
            </button>
            <a class="btn btn-secondary" href="<?= e($cancel_url) ?>">
                <?= view('icons/cancel') ?>
                <?= /* I18N: A button label. */
                I18N::translate('cancel') ?>
            </a>

            <?php if ($name_fact instanceof Fact && (Auth::isAdmin() || $tree->getPreference('SHOW_GEDCOM_RECORD'))) : ?>
                <a class="btn btn-link" href="<?= e(route(EditRawFactPage::class, ['xref' => $xref, 'fact_id' => $name_fact->id(), 'tree' => $tree->name()])) ?>">
                    <?= I18N::translate('Edit the raw GEDCOM') ?>
                </a>
            <?php endif ?>
        </div>
    </div>
</form>

<?php
#< ? = view('modals/on-screen-keyboard') ? >
#< ? = view('modals/ajax') ? >
#< ? = view('edit/initialize-calendar-popup') ? >
?>

<?php View::push('javascript') ?>
<script>
    function checkform() {
	alert("Foo");
    }
    function checkformX() {
	var ip = document.getElementsByTagName("input");
	var name = "";
	var givn = "";
	var surn = "";
	for (var i = 0; i < ip.length; i++) {
	    if (ip[i].id.indexOf("GIVN") === 0)
		givn = ip[i].value;
	    if (ip[i].id.indexOf("SURN") === 0)
		surn = ip[i].value;
	}
	if (givn != "") {
	    name += givn;
	}
	if (name != "") {
	    name += " ";
	}
	name += "/" . surn . "/";
	alert(name);
#	for (var i = 0; i < ip.length; i++) {
#	    if (ip[i].id.indexOf("NAME") === 0)
#		ip[i].value = givn + " /" + surn + "/";
#	}
        return false;
    }
</script>
<?php View::endpush() ?>

