<?php

use DISMaja\Webtrees\Module\UnlinkedIndividual\Http\UnlinkedAction;
use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Functions\FunctionsEdit;
use Fisharebest\Webtrees\Gedcom;
use Fisharebest\Webtrees\GedcomTag;
use Fisharebest\Webtrees\Http\RequestHandlers\EditRawFactPage;
use Fisharebest\Webtrees\Http\RequestHandlers\ManageTrees;
use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\SurnameTradition;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;
use Ramsey\Uuid\Uuid;

/**
 * @var Family|null     $family
 * @var string          $famtag
 * @var string          $gender
 * @var Individual|null $individual
 * @var Fact|null       $name_fact
 * @var string          $next_action
 * @var string          $title
 * @var Tree            $tree
 */

?>
<?php

    $cancel_url = route(TreePage::class, ['tree' => $tree->name()]);
    $xref       = 'new';

    // Creating a new name
    $name_fact_id = '';
    $namerec      = '';
    $name_fields  = [
        'GIVN' => '',
        'SURN' => '',
    ];

?>
<h2 class="wt-page-title"><?= $title ?></h2>

<form method="post" action="<?= e(route($next_action, ['tree' => $tree->name(), 'xref' => $xref, 'fact_id' => $name_fact ? $name_fact->id() : null])) ?>">
    <input type="hidden" name="fact_id" value="<?= e($name_fact_id) ?>">
    <input type="hidden" name="famtag" value="<?= e($famtag) ?>">
    <input type="hidden" name="gender" value="<?= $gender ?>">
    <input type="hidden" name="NAME" value="">
    <input type="hidden" name="NPFX" value="">
    <input type="hidden" name="SPFX" value="">
    <input type="hidden" name="NSFX" value="">
    <input type="hidden" name="NICK" value="">
    <input type="hidden" name="_AKA" value="">
    <input type="hidden" name="_MARNM" value="">
    <?= csrf_field() ?>

    <?php
    $SEXid  = 'SEX'  . Uuid::uuid4()->toString();
    $GIVNid = 'GIVN' . Uuid::uuid4()->toString();
    $SURNid = 'SURN' . Uuid::uuid4()->toString();
    ?>
    
    <div class="form-group row">
	<label class="col-sm-3 col-form-label" for="<?= $SEXid ?>">
	    <?= I18N::translate('Gender') ?>
	</label>
	<div class="col-sm-9">
	    <div class="form-check form-check-inline">
	        <input type="radio" class="form-check-input" name ="SEX" id="SEX-M" value="M" required="required">
		<label class="form-check-label" for="SEX-M">
		    <?= I18N::translate('Male') ?>
		</label>
	    </div>
	    <div class="form-check form-check-inline">
	        <input type="radio" class="form-check-input" name ="SEX" id="SEX-F" value="F" required="required">
		<label class="form-check-label" for="SEX-F">
		    <?= I18N::translate('Female') ?>
		</label>
	    </div>
	    <div class="form-check form-check-inline">
	        <input type="radio" class="form-check-input"  name ="SEX" id="SEX-U" value="F" required="required">
		<label class="form-check-label" for="SEX-U">
		    <?= I18N::translate('Unknown') ?>
		</label>
	    </div>
	</div>
    </div>

    <div class="form-group row">
	<label class="col-sm-3 col-form-label" for="<?= $GIVNid ?>">
	    <?= I18N::translate('Given names') ?>
	</label>
	<div class="col-sm-9">
	    <div class="input-group">
		<input class="form-control" type="text" id="<?= $GIVNid ?>" name="GIVN" value="">
	    </div>
	</div>
    </div>

    <div class="form-group row">
	<label class="col-sm-3 col-form-label" for="<?= $SURNid ?>">
	    <?= I18N::translate('Surname') ?>
	</label>
	<div class="col-sm-9">
	    <div class="input-group">
		<input class="form-control" type="text" id="<?= $SURNid ?>" name="SURN" value="">
	    </div>
	</div>
    </div>

    <div class="row form-group">
        <div class="col-sm-9 offset-sm-3">
            <button class="btn btn-primary" type="submit">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
	    <button class="btn btn-primary" type="submit" name="goto" value="new"> 
                <?= view('icons/save') ?>
                <?= I18N::translate('go to new individual') ?>
	    </button>
            <a class="btn btn-secondary" href="<?= e($cancel_url) ?>">
                <?= view('icons/cancel') ?>
		<?= I18N::translate('cancel') ?>
            </a>

            <?php if ($name_fact instanceof Fact && (Auth::isAdmin() || $tree->getPreference('SHOW_GEDCOM_RECORD'))) : ?>
                <a class="btn btn-link" href="<?= e(route(EditRawFactPage::class, ['xref' => $xref, 'fact_id' => $name_fact->id(), 'tree' => $tree->name()])) ?>">
                    <?= I18N::translate('Edit the raw GEDCOM') ?>
                </a>
            <?php endif ?>
        </div>
    </div>
</form>

